### ISSUE TITLE
panic when trying to get csme data with --versions flag

### ISSUE THREAD

**Issue by Stew-rt** [FrameworkComputer/framework-system#35]
I'm currently experiencing firmware update issues, so it might be related.
But I get a panic on `framework_lib/src/csme.rs:61:17`

when i run `framework_tool --versions`

Details:
![image](https://github.com/FrameworkComputer/framework-system/assets/40280034/0bd74b05-5940-457b-9bf9-b0ec4c1c7116)

**Comment by JohnAZoidberg** [comment]
Could you please `cat /sys/class/mei/mei0/fw_ver` and paste here what it shows?

On all systems I've tested on it shows three versions that are all the same. On yours apparently not.
Reference: https://github.com/torvalds/linux/blob/cf87f46fd34d6c19283d9625a7822f20d90b64a4/Documentation/ABI/testing/sysfs-class-mei#L58

**Comment by Stew-rt** [comment]
```
stewart@muh04 ~ % sudo cat /sys/class/mei/mei0/fw_ver
0:16.1.30.2269
0:16.1.30.2269
0:16.0.15.1810
```

**Comment by Stew-rt** [comment]
Full backtrace in case it's of any use:
```
[root@muh04 stewart]# export RUST_BACKTRACE=full
[root@muh04 stewart]# framework_tool --versions
UEFI BIOS
  Version:        03.08
  Release Date:   12/25/2023
EC Firmware
  Build version:  "hx30_v0.0.1-4ea1c89 2023-12-11 14:15:35 runner@fv-az1124-221"
  RO Version:     "hx30_v0.0.1-4ea1c89"
  RW Version:     "hx30_v0.0.1-4ea1c89"
  Current image:  RO
PD Controllers
  Right (01)
    Main   App:     0.1.44 (Notebook)
    Backup App:     0.1.44 (Notebook)
  Left  (23)
    Main   App:     0.1.44 (Notebook)
    Backup App:     0.1.44 (Notebook)
Retimers
  Left:           0x136 (310)
  Right:          0xCF (207)
CSME
thread 'main' panicked at 'assertion failed: fw_vers.iter().all(|&item| item == fw_vers[0])', framework_lib/src/csme.rs:61:17
stack backtrace:
   0:     0x581dc09f1990 - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x581dc09f1990 - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x581dc09f1990 - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x581dc09f1990 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x581dc0911dbe - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x581dc09d03c4 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x581dc09f2e87 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x581dc09f2e87 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x581dc09f2c25 - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x581dc09f3369 - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x581dc09f3369 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:688:13
  11:     0x581dc09f3014 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:577:13
  12:     0x581dc09f2fac - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x581dc09f2f81 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  14:     0x581dc08bd7d2 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  15:     0x581dc08bd8cc - core::panicking::panic::h056c466ab4571cf2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
  16:     0x581dc093d70c - framework_lib::commandline::run_with_args::h50dadf209f8659c6
  17:     0x581dc0963176 - framework_tool::main::hc6ef639b5f962f24
  18:     0x581dc0963386 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f65a91ea31e53a7
  19:     0x581dc096277a - main
  20:     0x79ecafe0cc88 - <unknown>
  21:     0x79ecafe0cd4c - __libc_start_main
  22:     0x581dc08c30b5 - _start
  23:                0x0 - <unknown>
```

**Comment by CodeAsm** [comment]
Your rightside retimers can be updated if you copy the retirmer23.cap from either the msi file or 3.06 efi update. this will not change the reported CSME versions i also have:
```
15:06:51 ✗ [codeasm@framework:~]$ cat  /sys/class/mei/mei0/fw_ver 
0:16.1.30.2269
0:16.1.30.2269
0:16.0.15.1810
```

**Comment by Stew-rt** [comment]
User Ray519 on the Framework Community site noted the following, and I think it might be insightful for this tool to be able to present this info properly:

"""
Just btw, when you use HWInfo under Windows to check ME firmware versions, there are 3 versions.
Main, Recovery and FITC. Main and Recovery always seem to match, FITC seems a much older version (maybe the one from the factory, don’t know). So my guess ist, that those 3 versions linux reports are just that. And across multiple non-framework machines it seems that the FITC version is never the version you updated with any ME update. So I think, only the first and maybe the second version in that version report are relevant to confirm a correct ME update.
"""

[Link to original post](https://community.frame.work/t/12th-gen-intel-core-bios-3-08-release/43244/429)

**Comment by JohnAZoidberg** [comment]
That seems, right. Thanks!
I'll update the code to behave correctly

**Comment by JohnAZoidberg** [comment]
@Stew-rt please try #38 and see if that works well on your system.

**Comment by Stew-rt** [comment]
@JohnAZoidberg - I'd likely say this order is in reverse:

```
stewart@muh04 ~/testing/framework-system (git)-[csme-version] % sudo target/debug/framework_tool --versions
[sudo] password for stewart: 
UEFI BIOS
  Version:        03.08
  Release Date:   12/25/2023
EC Firmware
  Build version:  "hx30_v0.0.1-4ea1c89 2023-12-11 14:15:35 runner@fv-az1124-221"
  RO Version:     "hx30_v0.0.1-4ea1c89"
  RW Version:     "hx30_v0.0.1-4ea1c89"
  Current image:  RO
PD Controllers
  Right (01)
    Main   App:     0.1.44 (Notebook)
    Backup App:     0.1.44 (Notebook)
  Left  (23)
    Main   App:     0.1.44 (Notebook)
    Backup App:     0.1.44 (Notebook)
Retimers
  Left:           0x136 (310)
  Right:          0x136 (310)
CSME
  Enabled:        true
  Version:        0:16.0.15.1810
  Recovery Ver:   0:16.1.30.2269
  Original Ver:   0:16.1.30.2269
```

**Comment by JohnAZoidberg** [comment]
Thanks... I remember I intentionally reversed it in the code today, but  I don't remember why... You're right. It's the wrong order.
I updated the PR.

**Comment by Stew-rt** [comment]
That looks more like it:

```
stewart@muh04 ~/testing/framework-system (git)-[csme-version] % sudo target/debug/framework_tool --versions
UEFI BIOS
  Version:        03.08
  Release Date:   12/25/2023
EC Firmware
  Build version:  "hx30_v0.0.1-4ea1c89 2023-12-11 14:15:35 runner@fv-az1124-221"
  RO Version:     "hx30_v0.0.1-4ea1c89"
  RW Version:     "hx30_v0.0.1-4ea1c89"
  Current image:  RO
PD Controllers
  Right (01)
    Main   App:     0.1.44 (Notebook)
    Backup App:     0.1.44 (Notebook)
  Left  (23)
    Main   App:     0.1.44 (Notebook)
    Backup App:     0.1.44 (Notebook)
Retimers
  Left:           0x136 (310)
  Right:          0x136 (310)
CSME
  Enabled:        true
  Version:        0:16.1.30.2269
  Recovery Ver:   0:16.1.30.2269
  Original Ver:   0:16.0.15.1810
```

Great stuff!
